// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqrqcsyrcsbfgjgwjcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcXJxY3N5cmNzYmZnamd3amNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTYwMzYsImV4cCI6MjA1Njk5MjAzNn0.DuJgpLKK1Gwn4FEom8Mj4OzroxGDeAtTuCtpMEQayYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);